server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RazibHossain/Microservice.git
          search-paths: Demo-Microservice-with-Spring-Boot-3/central-configuration-files
          clone-on-start: true
